#include<stdio.h>
#include<stdlib.h>
#include<time.h>//used for srand
#include<string.h>


typedef struct Human_ID{
char ID[50];//id number to be stored
char password[11];//generated by us of size 6;one extra size for null character
}pass;

void storedatainfile(FILE *store,pass a);
char SpecialChars();
char CapitalLetters();
char NormalLetters();
char NumberChars();

void createUser(){

    srand(time(NULL));//initialise srand to randomly generate passwords

    FILE *store=fopen("userDataServer.csv","a");//append the data
    if(store==NULL){
        printf("FILE NOT FOUND");
        exit(1);
    }

    pass a;//struct definition
    printf("ENTER YOUR ID NUMBER:");
    char string[50];
    scanf("%s",string);//these are unique to each human
    strcpy(a.ID,string);
    
    //checkpoint to see if this is the second time user is generating
    printf("WE WILL BE GENERATING A SIX DIGIT PASSWORD FOR YOU.\n");
    printf("ON THE DAY OF VOTING, YOU MUST CONFIRM YOUR IDENTITY BY INSERTING THIS.\n\n ");
    //generating password by calling individual functions.
    a.password[0]=CapitalLetters();
    a.password[1]=NormalLetters();
    a.password[2]=CapitalLetters();
    a.password[3]=SpecialChars();
    a.password[4]=SpecialChars();
    a.password[5]=NumberChars();
    a.password[6]=CapitalLetters();
    a.password[7]=NormalLetters();
    a.password[8]=NumberChars();
    a.password[9]=NormalLetters();
    a.password[10]='\0';

    for(int i=0;i<50;i++){
        printf("=");
    }
    printf("\n");
    printf("\n");

    storedatainfile(store,a);//storing password
    
    printf("%s\n",a.password);

    printf("\n");
    for(int i=0;i<50;i++){
        printf("=");
    }
    printf("\n");
    fclose(store);
}

void storedatainfile(FILE *store,pass a){
fprintf(store,"%s//%s\n",encrypt(a.ID, 5),encrypt(a.password, 5));//writing in file
}

char SpecialChars(){
    char special[]="#@!$-_&*~";
    return special[rand()%9];//randomlychoosefromthe9charactersgiven by me
}
char CapitalLetters(){
    return 'A'+rand()%26;//randomly choose from any 26
}
char NormalLetters(){
    return 'a'+rand()%26;
}
char NumberChars(){
    return '0'+rand()%10;
}